name: kustomize-job
description: Runs your build step as a kustomized kubernetes job
author: https://github.com/pr8kerl
requirements:
  - kubectl
  - kustomize
configuration:
  properties:
    name:
      type: string
    overlay:
      type: array
    debug:
      type: string
  required:
    - name
    - overlay
  additionalProperties: false
